---
kind: pipeline
type: docker
name: Autorestic Role Checks

steps:
  - name: ansible-lint + yamllint
    image: fuzzymistborn/docker-linting:latest
    environment:
    commands:
      - "ansible-lint ."
      - "yamllint ."

  - name: Send TG Notification
    image: appleboy/drone-telegram
    settings:
      token:
        from_secret: tg_token
      to:
        from_secret: tg_id
      format: html
      message: >
        {{#success build.status}}
          Build for <b>{{repo.name}}</b> was <b>successful</b>.  Check output <a href= '{{build.link}}'>here</a>
        {{else}}
          <b>WARNING</b>: Build for <b>{{repo.name}}</b> has <b>FAILED</b>!  Check status <a href= '{{build.link}}'>here</a>
        {{/success}}
    when:
      status: [ success, failure ]
