---
kind: pipeline
type: docker
name: Autorestic Role Lint

trigger:
  event:
    - push

steps:
  - name: ansible-lint + yamllint
    image: fuzzymistborn/docker-linting:latest
    commands:
      - "ansible-lint ."
      - "yamllint ."

  - name: Send TG Notification
    image: appleboy/drone-telegram
    settings:
      token:
        from_secret: tg_token
      to:
        from_secret: tg_id
      format: markdown
      message: "{{#success build.status}}✅  Build for `{{repo.name}}` was *successful*!{{else}}❌  Build for `{{repo.name}}` has *FAILED*!{{/success}} \n🌐  [Output]({{build.link}})\n📝  Commit: {{ commit.message }}"
    when:
      status: [ success, failure ]

---
kind: pipeline
type: docker
name: Autorestic Role Publish to Galaxy

trigger:
  event:
    - tag

steps:
  - name: Push
    image: fuzzymistborn/docker-linting:latest
    environment:
      GALAXY_API_KEY:
        from_secret: galaxy_api_key
    commands:
      - ansible-galaxy role import --api-key $GALAXY_API_KEY FuzzyMistborn ansible-role-autorestic

  - name: Send TG Notification
    image: appleboy/drone-telegram
    settings:
      token:
        from_secret: tg_token
      to:
        from_secret: tg_id
      format: markdown
      message: "{{#success build.status}}✅  Push to Ansible Galaxy for `{{repo.name}}` was *successful*!{{else}}❌  Push to Ansible Galaxy for `{{repo.name}}` has *FAILED*!{{/success}} \n🌐  [Output]({{build.link}})"
    when:
      status: [ success, failure ]