---
steps:
  - name: Push
    image: fuzzymistborn/docker-linting:latest
    environment:
      galaxy_api_key:
        from_secret: galaxy_api_key
    commands:
      - ansible-galaxy role import --api-key $galaxy_api_key FuzzyMistborn ansible-role-autorestic

  - name: Notify Success
    image: appleboy/drone-telegram
    settings:
      token:
        from_secret: tg_token
      to:
        from_secret: tg_id
      format: markdown
      message: "✅  Push to Ansible Galaxy for `${CI_REPO_NAME}` was *successful*!\n🌐  [Output](${CI_PIPELINE_URL})"
    when:
      - event: release
        status: [success]

  - name: Notify Failure
    image: appleboy/drone-telegram
    settings:
      token:
        from_secret: tg_token
      to:
        from_secret: tg_id
      format: markdown
      message: "❌  Push to Ansible Galaxy for `${CI_REPO_NAME}` has *FAILED*!\n🌐  [Output](${CI_PIPELINE_URL})"
    when:
      - event: release
        status: [failure]

when:
  event: release